---
- name: apt-get update
  sudo: yes
  apt: update_cache=yes

- name: Install packages from apt
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
      - unzip
      - curl
      - libcurl4-gnutls-dev
      - python-pip
      - python-pycurl
      - python-psycopg2

- name: Install python packages
  pip: name={{ item }} state=latest
  with_items:
      - docker-py