#hosts:local
#connection: local
- hosts: all
  sudo: True

  roles:
    - common
    #https://github.com/angstwad/docker.ubuntu
    - angstwad.docker_ubuntu

  tasks:

    #https://index.docker.io/u/helmi03/docker-postgis/
    #http://docs.ansible.com/docker_module.html
    - name: install postgres + postgis in docker
      action: docker image=helmi03/docker-postgis ports=5432:5432 name=postgres

    - name: create anax database
      action: postgresql_db name=anax login_host=127.0.0.1 login_user=docker login_password=docker
      # action: postgresql_db name=anax template=template_postgis login_host=127.0.0.1 login_user=docker login_password=docker

    - name: ensure user has access to database
      action: postgresql_user db=anax user=anax_user password=anax_password
                role_attr_flags=CREATEDB,CREATEROLE,SUPERUSER
                login_user=docker login_password=docker priv=ALL login_host=127.0.0.1

    - name: setup local db access
      sudo: False
      local_action: command echo "127.0.0.1:5432:anax:anax_user:anax_password" > ~/.pgpass

    - name: change local db acces file permissions
      sudo: False
      local_action: command chmod 0600 ~/.pgpass

    - name: populate anax database
      sudo: False
      local_action: shell psql -h 127.0.0.1 anax anax_user < tmp/db.bak

    #this is using the private docker repo in provisioning/docker-registry, running make build
    #use  netstat -rn within vagrant ssh to find the gateway (ie the outside address)

    #todo: connect up to db via links: http://docs.docker.io/use/working_with_links_names/
    - name: install anaximander in docker
      action: docker image=10.0.2.2:5000/anaximander:0.2.0-dev.1 ports=6000:8000 name=anaximander

    - name: prepare local tmp
      sudo: False
      local_action: file path=tmp state=directory

    - name: get retred ghost theme
      sudo: False
      local_action: get_url url=https://github.com/twistedvisions/retred-ghost-theme/archive/0.1.0.zip dest=tmp/theme.zip

    - name: prepare ghost theme dir
      action: file path=/var/ghost-override/content/themes state=directory

    - name: copy theme
      action: unarchive src=tmp/theme.zip dest=/var/ghost-override/content/themes

    - name: rename theme
      action: command mv /var/ghost-override/content/themes/retred-ghost-theme-0.1.0
                         /var/ghost-override/content/themes/retred-ghost-theme

    - name: install blog in docker
      action: docker image=dockerfile/ghost ports=6010:2368
                name=blog volumes=/var/ghost-override:/ghost-override

      #ansible vagrant -i hosts.ini --private-key=~/.vagrant.d/insecure_private_key -u vagrant  -m docker -a "image=helmi03/docker-postgis"
      #ansible vagrant -i hosts.ini --private-key=~/.vagrant.d/insecure_private_key -u vagrant  -m docker -a "image=localhost:5000/twistedvisions/anaximander"

